export const LINKS = {
  github: 'https://github.com/sergiogmr',
  linkedin: 'https://www.linkedin.com/in/sergiogmr/',
  mail: 'mailto:sergiogmr+portfolio@icloud.com',
  acesports: 'https://acesports.vercel.app/',
  discord: 'https://discordapp.com/users/299882015367495682',
  twitter: 'https://x.com/sergiogmr',
  manfred: 'https://www.getmanfred.com/perfil/sergiogmr',
}

export const STACK = [
  'PHP',
  'Laravel',
  'JavaScript',
  'TypeScript',
  'React',
  'React Native',
  'Vue',
  'Git',
  'CSS',
  'Tailwind CSS',
  'Bootstrap',
]

export const EXPERIENCE = {
  es: [
    {
      company: 'Freelance',
      location: 'Las Palmas, España',
      position: 'Project Manager',
      link: 'https://projects.todo-lux.com/',
      start: '12/2023',
      end: 'Actualmente',
      tasks: [
        'Análisis de las necesidades del sistema',
        'Diseño de la base de datos',
        'Desarrollo del BackOffice y el sistema de backups',
        'Diseño del sistema de importación de archivos BMCAT',
        'Desarrollo del frontend',
        'Lógica de eventos y colas',
        'Desarrollo usando Laravel, Livewire, Filamentphp',
      ],
    },
    {
      company: 'Freelance',
      location: 'Las Palmas, España',
      position: 'FullStack Developer',
      link: 'https://proyectolibera.org/caracterizacion-residuos/basuraleza',
      start: '06/2020',
      end: '10/2020',
      tasks: [
        'Desarrollando el backend de esta aplicación con Laravel',
        'Desarrollando la aplicación móvil con QuasarFramework',
        'Desarrollando una aplicación web con Laravel y Livewire',
        'Desarrollando una aplicación móvil con QuasarFramework',
        'Desarrollando el backend para esta aplicación con Laravel',
      ],
    },
    {
      company: 'Freelance | Tecandu S.L.',
      location: 'España',
      position: 'FullStack Developer',
      link: 'https://solutec.pccom.ai/',
      start: '01/2023',
      end: '04/2024',
      tasks: [
        'Adaptación de tecnologías a los nuevos tiempos',
        'Coordinación del equipo de desarrollo y del equipo DevOps',
        'Estudio y rediseño de la base de datos y desarrollo para la transferencia sin pérdida de datos o funcionalidad',
        'Desarrollo de una nueva versión, v3, de la API utilizando Laravel Sanctum',
        'Planificación de las pruebas faltantes y su implementación',
        'Desarrollo CI-CD con Github Actions y Plesk',
      ],
    },
    {
      company: 'Tca-Tik',
      location: 'Las Palmas de Gran Canaria, España',
      position: 'FullStack Developer',
      link: 'https://tcatik.com/',
      start: '05/2019',
      end: '02/2020',
      tasks: [
        'Desarrollador Frontend con VueJS, jQuery, Bootstrap',
        'Desarrollador Backend con Laravel',
        'Trabajando con algunos productos de la empresa',
      ],
    },
  ],
  en: [
    {
      company: 'Freelance',
      location: 'Las Palmas, Spain',
      position: 'Project Manager',
      link: 'https://projects.todo-lux.com/',
      start: '2023/12',
      end: 'Current',
      tasks: [
        'Analysis of system requirements',
        'Database design',
        'Development of BackOffice and backup system',
        'Design of file import system for BMCAT',
        'Frontend development',
        'Event and queue logic',
        'Development using Laravel, Livewire, Filamentphp',
      ],
    },
    {
      company: 'Freelance',
      location: 'Las Palmas, Spain',
      position: 'FullStack Developer',
      link: 'https://proyectolibera.org/caracterizacion-residuos/basuraleza',
      start: '2020/06',
      end: '2020/10',
      tasks: [
        'Developing the backend of this application with Laravel',
        'Developing the mobile application with QuasarFramework',
        'Developing a web application with Laravel and Livewire',
        'Developing a mobile application with QuasarFramework',
        'Developing the backend for this application with Laravel',
      ],
    },
    {
      company: 'Freelance | Tecandu S.L.',
      location: 'Spain',
      position: 'FullStack Developer',
      link: 'https://solutec.pccom.ai/',
      start: '2023/01',
      end: '2024/04',
      tasks: [
        'Adaptation of technologies to new standards',
        'Coordination of the development team and the DevOps team',
        'Study and redesign of the database and development for lossless data transfer',
        'Development of a new version, v3, of the API using Laravel Sanctum',
        'Planning of pending tests and their implementation',
        'CI-CD development with Github Actions and Plesk',
      ],
    },
    {
      company: 'Tca-Tik',
      location: 'Las Palmas de Gran Canaria, Spain',
      position: 'FullStack Developer',
      link: 'https://tcatik.com/',
      start: '2019/05',
      end: '2020/02',
      tasks: [
        'Frontend development with VueJS, jQuery, Bootstrap',
        'Backend development with Laravel',
        "Working with some of the company's products",
      ],
    },
  ],
}
